<?php
// Auto-generated by api/permissions-update.php
// Do not edit manually — this file is overwritten on every permission save.
// If this file is empty/stub, PermissionService will fall back to live DB queries.
return [];
