CREATE TABLE IF NOT EXISTS material_goods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(120) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    category VARCHAR(120) DEFAULT NULL,
    subcategory VARCHAR(120) DEFAULT NULL,
    base_unit VARCHAR(40) NOT NULL DEFAULT 'pcs',
    estimate_unit VARCHAR(40) NOT NULL DEFAULT 'pcs',
    unit_conversion_factor DECIMAL(12,4) NOT NULL DEFAULT 1.0000,
    gst_rate DECIMAL(6,2) NOT NULL DEFAULT 18.00,
    default_wastage_pct DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    labor_model ENUM('none','flat','per_unit') NOT NULL DEFAULT 'none',
    labor_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    visibility ENUM('private','public') NOT NULL DEFAULT 'public',
    specification_url VARCHAR(255) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_material_goods_sku (sku),
    KEY idx_material_goods_category (category),
    KEY idx_material_goods_status (status),
    KEY idx_material_goods_visibility (visibility)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_price_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    goods_id INT NOT NULL,
    vendor_id INT DEFAULT NULL,
    price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(12) NOT NULL DEFAULT 'INR',
    effective_at DATETIME DEFAULT NULL,
    quote_type ENUM('quote','purchase','actual_closeout') NOT NULL DEFAULT 'quote',
    source_note TEXT DEFAULT NULL,
    expiry_date DATE DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_material_price_goods (goods_id),
    KEY idx_material_price_vendor (vendor_id),
    KEY idx_material_price_effective (effective_at),
    CONSTRAINT fk_material_price_goods FOREIGN KEY (goods_id) REFERENCES material_goods (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_price_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_vendor_quotes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    goods_id INT NOT NULL,
    vendor_id INT NOT NULL,
    quoted_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(12) NOT NULL DEFAULT 'INR',
    minimum_order_qty DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    lead_time_days INT NOT NULL DEFAULT 0,
    last_quote_date DATE DEFAULT NULL,
    valid_until DATE DEFAULT NULL,
    preferred_supplier TINYINT(1) NOT NULL DEFAULT 0,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_material_quote_goods (goods_id),
    KEY idx_material_quote_vendor (vendor_id),
    CONSTRAINT fk_material_quote_goods FOREIGN KEY (goods_id) REFERENCES material_goods (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_quote_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_estimates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    estimate_code VARCHAR(80) NOT NULL,
    project_id INT DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    status ENUM('draft','internal_review','sent_to_client','client_approved','revision_requested','closed') NOT NULL DEFAULT 'draft',
    currency VARCHAR(12) NOT NULL DEFAULT 'INR',
    markup_pct DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    contingency_pct DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    tax_mode ENUM('exclusive','inclusive','line_item') NOT NULL DEFAULT 'exclusive',
    notes TEXT DEFAULT NULL,
    current_version_id INT DEFAULT NULL,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_material_estimate_code (estimate_code),
    KEY idx_material_estimate_status (status),
    KEY idx_material_estimate_project (project_id),
    KEY idx_material_estimate_created_by (created_by),
    CONSTRAINT fk_material_estimate_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL,
    CONSTRAINT fk_material_estimate_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_estimate_versions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    estimate_id INT NOT NULL,
    version_number INT NOT NULL,
    header_snapshot LONGTEXT DEFAULT NULL,
    subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    gst_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    grand_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_material_estimate_versions_estimate (estimate_id),
    KEY idx_material_estimate_versions_created_by (created_by),
    CONSTRAINT fk_material_estimate_versions_estimate FOREIGN KEY (estimate_id) REFERENCES material_estimates (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_estimate_versions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_estimate_sections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    version_id INT NOT NULL,
    section_title VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    notes TEXT DEFAULT NULL,
    KEY idx_material_estimate_sections_version (version_id),
    CONSTRAINT fk_material_estimate_sections_version FOREIGN KEY (version_id) REFERENCES material_estimate_versions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_estimate_lines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    version_id INT NOT NULL,
    section_id INT NOT NULL,
    line_number INT NOT NULL DEFAULT 0,
    goods_id INT DEFAULT NULL,
    vendor_id INT DEFAULT NULL,
    vendor_quote_id INT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    quantity DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    wastage_pct DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    effective_qty DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    base_unit VARCHAR(40) DEFAULT NULL,
    estimate_unit VARCHAR(40) DEFAULT NULL,
    conversion_factor DECIMAL(12,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    material_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    labor_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    markup_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    contingency_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    taxable_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    gst_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    gst_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_material_estimate_lines_version (version_id),
    KEY idx_material_estimate_lines_section (section_id),
    KEY idx_material_estimate_lines_goods (goods_id),
    CONSTRAINT fk_material_estimate_lines_version FOREIGN KEY (version_id) REFERENCES material_estimate_versions (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_estimate_lines_section FOREIGN KEY (section_id) REFERENCES material_estimate_sections (id) ON DELETE CASCADE,
    CONSTRAINT fk_material_estimate_lines_goods FOREIGN KEY (goods_id) REFERENCES material_goods (id) ON DELETE SET NULL,
    CONSTRAINT fk_material_estimate_lines_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE SET NULL,
    CONSTRAINT fk_material_estimate_lines_vendor_quote FOREIGN KEY (vendor_quote_id) REFERENCES material_vendor_quotes (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_code VARCHAR(120) NOT NULL,
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(120) DEFAULT NULL,
    tags TEXT DEFAULT NULL,
    style_tags TEXT DEFAULT NULL,
    software_targets TEXT DEFAULT NULL,
    source_file VARCHAR(255) DEFAULT NULL,
    version_label VARCHAR(120) DEFAULT NULL,
    preview_url VARCHAR(255) DEFAULT NULL,
    license_notes TEXT DEFAULT NULL,
    goods_id INT DEFAULT NULL,
    export_formats TEXT DEFAULT NULL,
    status ENUM('draft','active','archived') NOT NULL DEFAULT 'active',
    visibility ENUM('private','public') NOT NULL DEFAULT 'public',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_material_assets_code (asset_code),
    KEY idx_material_assets_goods (goods_id),
    KEY idx_material_assets_status (status),
    CONSTRAINT fk_material_assets_goods FOREIGN KEY (goods_id) REFERENCES material_goods (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;